### ISSUE TITLE
overridden fields not properly handled in generated code

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#230] opened 2015-06-17 20:40 UTC
On the VM, this prints "hello\nworld".  On DDC, "hello\n\hello".  In the generated code, A's constructor is overwriting the value written by B's constructor.

```dart
class A {
  var x = "hello";
  void show() => print(x);
}

class B extends A {
  var x = "world";
}

var b = new B();
var a = new A();

void main() {
  a.show();
  b.show();
}
```

**Comment by vsmenon** [comment] 2015-06-17 20:41
We've also discussed forbidding field overrides.  That's the other way we can go with this.

**Comment by jmesserly** [comment] 2015-06-17 21:10
this is a dupe of https://github.com/dart-lang/dev_compiler/issues/52 right?

**Closed by jmesserly** 2015-06-17 21:10 UTC
Labels: bug, js
