### ISSUE TITLE
Deferred loading throws runtime error

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#523] opened 2016-04-25 19:24 UTC
The following code breaks at runtime:

```dart
import 'defer1.dart' deferred as defer1;

void main() {
  print('hello');
  defer1.loadLibrary().then((_) {
        defer1.main();
      });
}
```

An initial solution could eagerly load.

**Comment by jmesserly** [comment] 2016-04-25 20:08
dupe of https://github.com/dart-lang/dev_compiler/issues/305 :)

**Closed by jmesserly** 2016-04-25 20:08 UTC
Labels: P2 medium
