### ISSUE TITLE
"build_sdk.dart --modules es6" generates invalid dart_sdk.js

### ISSUE THREAD

**Issue by TheBosZ** [dart-lang/dev_compiler#562] opened 2016-05-11 16:48 UTC
If I run the command (on windows):
```dart tool\build_sdk.dart --dart-sdk tool\generated_sdk --modules es6 -o dart_sdk.js```

the generated file has 3 definitions of ```const _iterable```.

The ```--modules node``` version instead has different names for the 3 instances.

**Comment by jmesserly** [comment] 2016-05-11 16:52
I believe this is caused by https://github.com/dart-lang/dev_compiler/issues/512

**Comment by TheBosZ** [comment] 2016-05-11 16:53
That would explain why I couldn't find an issue for it! Feel free to close if necessary.

**Comment by jmesserly** [comment] 2016-09-13 23:37
going to close as a dupe of #512

**Closed** 2016-09-13 23:38 UTC
Labels: area-dev-compiler
