### ISSUE TITLE
transformer tests frequently hanging on travis

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#458] opened 2016-02-22 16:40 UTC
The transformer test appears to be hanging at the end for some reason:

https://travis-ci.org/dart-lang/dev_compiler/builds/110512663

Disabling for now.

@ochafik - can you take a look?

**Comment by jmesserly** [comment] 2016-02-22 16:53
I wondered if it was actually hanging, or if our tests happen to be running close to the 10 minute mark, and transformer test pushes it over the limit.

**Comment by vsmenon** [comment] 2016-02-22 16:58
As best as I can tell from the logs, it prints the last expected line every time.  I've never seen it hang locally though.

**Comment by vsmenon** [comment] 2016-02-22 17:29
Hmm, red again.  I think your right about timing.

The addition of dart:html (+ all the other dom libs) made are tests quite a bit slower, but pass/fail has been sporadic.

**Comment by vsmenon** [comment] 2016-02-25 15:21
Hmm, my change does force resolution of dart:html even for tests that don't use it.  This may be slowing down the transformer tests.

**Comment by jmesserly** [comment] 2016-02-25 17:23
> Hmm, my change does force resolution of dart:html even for tests that don't use it. This may be slowing down the transformer tests.

Ah, yeah, that would do it.

In theory, we should be able to avoid this problem: if a library doesn't (transitively) depend on dart:html then we shouldn't need to know about it.

(We would still need to mark interfaces as being implementable by native types.)

**Comment by ochafik** [comment] 2016-03-01 06:32
Doesn't seem like the transformer tests were the cause, as travis still often times out despite them being [disabled](https://github.com/dart-lang/dev_compiler/commit/bb1b557746e379ede7b16d959ebf9831e34e0433) ([example](https://travis-ci.org/dart-lang/dev_compiler/builds/112072590)).

I'll send a PR to reenable them with some logs / separate envs to better isolate failures.

**Comment by jmesserly** [comment] 2016-03-16 17:01
should be able to close this one for now

**Closed by jmesserly** 2016-03-16 17:01 UTC
Labels: test
