### ISSUE TITLE
remove unneeded dart.js file when build html files

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#437] opened 2016-01-29 18:37 UTC
We currently leave `dart.js` scripts in place when we build html files (and convert `application/dart` scripts).  This triggers a missing file error when we serve apps.

Alternatively, we could package the actual runtime & sdk in a single `dart.js` file.

**Comment by jmesserly** [comment] 2016-08-22 15:46
dupe of #90

**Closed by jmesserly** 2016-08-22 15:46 UTC
Labels: bug, duplicate, html
