### ISSUE TITLE
Support extension-style calling conventions on possibly native JS objects

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#148] opened 2015-04-22 16:20 UTC
Methods on String, int, double, bool, num, and (because it may be one of the previous) Object need to be generated differently.

E.g., instead of:
```javascript
str.hashCode;
```
generate:
```javascript
core.String.hashCode(str);
```

@jacob314 @jmesserly We're handling List and other potentially native interfaces differently.  Should we try to be consistent?  For the most part, the above are sealed types, so it may make sense to be different.

Object is an interesting case.  E.g., we could go:

```javascript
core.Object.hashCode(obj);
```

and dispatch appropriately.  I'll start working on this.  Let me know if you're already looking at something similar.

**Comment by jmesserly** [comment] 2015-04-22 16:23
dupe of #40 :)

**Closed by jmesserly** 2015-04-22 16:23 UTC
Labels: bug, js
